### PR TITLE
Add point totals

### LINKED ISSUE #61: Add proper point totals
## User Story
As a user, I would like to see the in-game leaderboard so that I can see how everyone is performing.

### PR DESCRIPTION
**Pull request by omarTl**

### CODE REVIEW

**Comment by JonathanCMitchell** [comment]
Fails Travis CI test. Did you change the query structure?

**Comment by JonathanCMitchell** [comment]
After line https://github.com/CS130-W20/team-A1/blob/master/server/test_gamemanager.py#L67 add `del q["if_valid"]` so make structure same as before

**Comment by omarTl** [comment]
@JonathanCMitchell did that, thanks for the heads up on the failing build

**Comment by JonathanCMitchell** [comment]
Must do same modification in test_mutation as you did in test_gamemanager

**Comment by omarTl** [comment]
Just did, hopefully this will pass the build this time

**Pull request merged**
